In [7]:
import numpy as np

In [8]:
my_lst=[1,2,3,4,5]
my_array=np.array(my_lst)
print(my_array)

[1 2 3 4 5]


In [9]:
type(my_array)

numpy.ndarray

In [10]:
my_lst1 = [1,2,3,4,5]
my_lst2 = [6,7,8,9,10]
my_lst3 = [11,12,13,14,15]

arr = np.array([my_lst1, my_lst2, my_lst3])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [11]:
arr[2]

array([11, 12, 13, 14, 15])

In [12]:
arr[1:,:2]

array([[ 6,  7],
       [11, 12]])

In [15]:
arr[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [17]:
arr1 = arr[arr >5]

In [18]:
arr1

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
print(arr)
print("-------")
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------
[ 6  7  8  9 10 11 12 13 14 15]


In [22]:
arr.shape

(3, 5)

In [23]:
arr_shape = arr.reshape(5,3)
print(arr_shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [24]:
arr3 = np.arange(0,10).reshape(2,5)
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
arr4 = np.arange(0,10).reshape(2,5)
print(arr4)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
arr3*arr4

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [27]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.random.rand(2,3)

array([[0.62925446, 0.66696526, 0.73526421],
       [0.1669468 , 0.4413583 , 0.6848312 ]])

In [29]:
np.random.randint(0,10,size=(3,4))

array([[6, 9, 7, 7],
       [3, 9, 5, 8],
       [7, 0, 3, 3]])

In [31]:
np.random.randint(low=5, high=100, size=(10,10))

array([[27, 96, 25, 30,  7, 79, 12, 29, 75, 11],
       [44, 47, 25, 20, 19, 40, 44, 10, 18, 66],
       [78, 63, 88, 24, 26, 29, 25, 52, 47, 38],
       [88, 98, 75, 72, 76, 61, 61, 18, 60, 10],
       [24, 20, 91, 96, 24, 61, 46, 51, 24, 61],
       [53, 62, 56, 26, 17, 21, 64, 39, 10, 11],
       [95, 32, 55, 58, 69, 92, 42, 84, 35, 36],
       [51, 66, 61, 85,  9, 84, 13, 15, 54, 78],
       [33, 18, 75, 91, 49, 39, 60, 22, 58, 66],
       [39, 91, 15, 25, 84, 11, 15, 82, 36, 83]])

In [33]:
low = 1
high = 1000

possible_numbers = np.arange(low, high)
random_numbers = np.random.choice(possible_numbers, size=(10,10), replace=False)
random_numbers

array([[278, 932, 803, 422,  77, 693, 565, 957, 245, 252],
       [675, 880, 799, 383, 916, 812, 379, 511, 371, 489],
       [526, 898, 939, 186,  88, 255, 244,  37, 903,  72],
       [685, 978, 796, 127, 475, 423, 923, 286, 894, 731],
       [  3, 704, 789, 925, 415, 733, 153, 454, 530, 560],
       [904,  64, 457, 765, 581,  91, 107,  79, 205, 210],
       [ 55, 413, 949, 312, 240, 883, 572,  51,  57, 763],
       [788, 906,  35, 397, 295, 564, 276, 965, 284,  56],
       [ 36, 438, 723,  60, 824, 614, 409, 430, 699, 464],
       [315, 326,  43, 805, 534, 647, 376, 201, 541, 827]])

In [34]:
index = np.where(random_numbers ==475)
print(index)

(array([3], dtype=int64), array([4], dtype=int64))


In [35]:
random_numbers[3,4]

475

In [36]:
random_numbers[3,4] = 500

In [37]:
random_numbers

array([[278, 932, 803, 422,  77, 693, 565, 957, 245, 252],
       [675, 880, 799, 383, 916, 812, 379, 511, 371, 489],
       [526, 898, 939, 186,  88, 255, 244,  37, 903,  72],
       [685, 978, 796, 127, 500, 423, 923, 286, 894, 731],
       [  3, 704, 789, 925, 415, 733, 153, 454, 530, 560],
       [904,  64, 457, 765, 581,  91, 107,  79, 205, 210],
       [ 55, 413, 949, 312, 240, 883, 572,  51,  57, 763],
       [788, 906,  35, 397, 295, 564, 276, 965, 284,  56],
       [ 36, 438, 723,  60, 824, 614, 409, 430, 699, 464],
       [315, 326,  43, 805, 534, 647, 376, 201, 541, 827]])